[package]
name = "gameboy_emolator"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15"
minifb = "0.25"
ringbuf = "0.4.8"
serde = { version = "1.0.147", features = ["derive"] }
toml = "0.5.9"
